import { useState } from "react";
import { useAuth } from "../../context/AuthContext";
import { API_BASE_URL } from "../../api/apiConfig";
import { fetchJson } from "../../api/bookingStatus";
import { indiaDateString } from "../../utils/bookingDate";
import ModalFrame from "./ModalFrame";

export default function SessionChangeRequest({appointmentId,onClose,counsellor}) {
  const {token}=useAuth(); const [type,setType]=useState("reschedule"); const [date,setDate]=useState(""); const [time,setTime]=useState(""); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState(null);
  const submit=async event=>{event.preventDefault();setBusy(true);setError("");try{setResult(await fetchJson(`${API_BASE_URL}/api/session-support/appointments/${encodeURIComponent(appointmentId)}/requests`,{method:"POST",...(counsellor?{credentials:"include"}:{}),headers:{"Content-Type":"application/json",...(!counsellor?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({type,reason,preferredDate:date,preferredTime:time})}));}catch(error){setError(error.message);}finally{setBusy(false);}};
  return <ModalFrame isOpen onClose={onClose} closeDisabled={busy} title="Request a session change." description="The team will review your request. Your existing session remains scheduled until a change is confirmed.">{result ? <><p role="status" className="form-success">{result.message}</p><p className="text-xs text-gray-500 mt-4">Request reference: {result.requestId}</p><button className="button button-primary mt-5" onClick={onClose}>Done</button></> : <form className="form-stack" onSubmit={submit}><label><span className="field-label">Request type</span><select className="field-input" value={type} onChange={event=>setType(event.target.value)}><option value="reschedule">Reschedule session</option><option value="cancel">Cancel session</option></select></label>{type==="reschedule" && <div className="grid grid-cols-2 gap-3"><label><span className="field-label">Preferred date</span><input className="field-input" type="date" min={indiaDateString()} required value={date} onChange={event=>setDate(event.target.value)}/></label><label><span className="field-label">Preferred time (IST)</span><input className="field-input" type="time" required value={time} onChange={event=>setTime(event.target.value)}/></label></div>}<label><span className="field-label">Reason (optional)</span><textarea className="field-input" rows={3} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label><p className="text-xs text-gray-500">Requests made within 24 hours may be subject to the cancellation policy. Refunds are not processed automatically. <a href="/privacy-policy" className="underline">Read the policy</a>.</p>{error && <p role="alert" className="form-error">{error}</p>}<button className="button button-primary" disabled={busy}>{busy ? "Saving request..." : "Submit request"}</button></form>}</ModalFrame>;
}
